try {
    myFunction();
} catch (e) {
    // console.log(e.message)
    // console.log(e.name)
    // console.log(e instanceof ReferenceError)
    // console.log(e instanceof TypeError)
} finally {
    //this runs no matter what
}